"""empty message

Revision ID: 05e84f0201ff
Revises: d6b5ee7a5473
Create Date: 2018-11-02 14:57:45.632907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e84f0201ff'
down_revision = 'd6b5ee7a5473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_registrs_regcode', table_name='registrs')
    op.drop_table('registrs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrs',
    sa.Column('regcode', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('sepa', sa.VARCHAR(length=18), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('name_before_quotes', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('name_in_quotes', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('name_after_quotes', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('without_quotes', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('regtype', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('regtype_text', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('type_text', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('registered', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('terminated', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('closed', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('addressid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('region', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('atvk', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('reregistration_term', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('regcode', name='registrs_pkey')
    )
    op.create_index('ix_registrs_regcode', 'registrs', ['regcode'], unique=True)
    # ### end Alembic commands ###
